spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
    password: kadima01
    
  jpa:
    properties:
     hibernate:  
      ddl-auto: create   
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
