spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
    password: kadima01 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
     hibernate:  
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
      
